// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortBridgeShipping.Data;

#nullable disable

namespace PortBridgeShipping.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("PortBridgeShipping.MVVM.Models.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContainerNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContainerType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ContainerWeight")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDirty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RouteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContainerNumber")
                        .IsUnique();

                    b.HasIndex("RouteId");

                    b.HasIndex("StatusId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("PortBridgeShipping.MVVM.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDirty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("PortBridgeShipping.MVVM.Models.RouteSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDirty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RouteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Transport")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RouteId", "Order")
                        .IsUnique();

                    b.ToTable("RouteSegments");
                });

            modelBuilder.Entity("PortBridgeShipping.MVVM.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("PortBridgeShipping.MVVM.Models.Container", b =>
                {
                    b.HasOne("PortBridgeShipping.MVVM.Models.Route", "Route")
                        .WithMany("Containers")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortBridgeShipping.MVVM.Models.Status", "Status")
                        .WithMany("Containers")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PortBridgeShipping.MVVM.Models.RouteSegment", b =>
                {
                    b.HasOne("PortBridgeShipping.MVVM.Models.Route", "Route")
                        .WithMany("Segments")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("PortBridgeShipping.MVVM.Models.Route", b =>
                {
                    b.Navigation("Containers");

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("PortBridgeShipping.MVVM.Models.Status", b =>
                {
                    b.Navigation("Containers");
                });
#pragma warning restore 612, 618
        }
    }
}
